### ISSUE TITLE
Class Admin_Controller not found

### ISSUE THREAD

**Issue by markyie** [gieart87/ci-blog#1]
Maaf gan dengan bahasanya... saya dari malaysia.
saya click "General Setting" (link -> ../index.php/admin/settings) tapi keluar error seperti di bawah :
---
A PHP Error was encountered

Severity: Error

Message: Class 'Admin_Controller' not found

Filename: controllers/Settings.php

Line Number: 4

Backtrace:
---

mohon bantuan.
Terim kasih.

**Comment by gieart87** [comment]
Terima kasih gan atas masukkannya..
Memang untuk fitur general setting belum saya kerjakan gan. Blum ada kesempatan. Ke depan saya akan coba kerjakan utk fitur general setting ini.

Terima kasih.
