### ISSUE TITLE
Fatal error: Class 'Admin_Controller' not found in

### ISSUE THREAD

**Issue by terzweb** [gieart87/ci-blog#2]
Hello and thanks so much for the great  script!
The Admin panel General Setting Link have a error.
http://products.gie-art.com/ci-blog/index.php/admin/settings

Can anyone with ci-blog experience help with this please?

**Comment by gieart87** [comment]
Hi @terzweb ,
Thanks for trying this blogging script :)
About the fatal error on Setting.. I've not completed this feature before. But I've fixed just now, so You should update your local source with the fresh updated one. Hope this will help you :)
