### ISSUE TITLE
why cannot go to signin page? just stuck in homepage

### ISSUE THREAD

**Issue by aryayudha** [gieart87/ci-blog#5]
i cannot click signin menu, and just stuck in homepage

**Comment by Emanuele20** [comment]
application/config/config.php at line 26-- $config['base_url'] = 'http://www.yoururl/yourfolder/';

**Comment by gieart87** [comment]
@aryayudha  Hi Arya.. just add => index.php/users/signin at your home url. It shoult like this http://products.gie-art.com/ci-blog/index.php/users/signin. 

Thanks.
