### ISSUE TITLE
Proses Instalasi

### ISSUE THREAD

**Issue by Arya2000** [gieart87/ci-blog#6]
Saya menemukan pesan kesalahan setelah proses instalasi selesai da menunju ke halaman utama (http://localhost/ci-blog-master/)
berikut pesan kesalahannya:
Fatal error: Can't use method return value in write context in C:\xampp\ci-blog-master\application\views\themes\default\right_sidebar.php on line 7

**Comment by gieart87** [comment]
@Arya2000 apakah sudah terpecahkan maslahnya mas? mohon maaf baru sempat balas :|

**Comment by gierg** [comment]
bagaimana cara saya untuk mengakses halaman/login admin nya?

**Comment by gieart87** [comment]
Gini mas @gierg 
http://localhost/ci-blog/index.php/signin

**Comment by onehied** [comment]
gan boleh di shared file data yg di controller soal'y saya lihat di github nga ada, buat belajar gan
Thanks
